### ISSUE TITLE
onEvent argument should be a function

### ISSUE THREAD

**Issue by essivision** [rodrigogs/mysql-events#3]
I install your plugin and use your example, but show me error:
```
Error: onEvent argument should be a function
    at MySQLEvents.addTrigger (C:\wamp64\www\upport54\services\call_popup\node_modules\@rodrigogs\mysql-events\lib\MySQLEvents.js:166:46)
    at program (C:\wamp64\www\upport54\services\call_popup\file.js:14:14)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by rodrigogs** [comment]
Sorry. The example was not updated. The `callback` argument was changed to `onEvent`.

**Comment by houyanchao** [comment]
![image](https://user-images.githubusercontent.com/9604104/47332633-72012300-d6b2-11e8-98b0-f1259158cbab.png)

After starting the monitor, I will encounter this error in about 10 hours. It has appeared many times.
